apiVersion: 1

datasources:
  - name: Supabase
    type: postgres
    access: proxy

    url: aws-0-ap-northeast-1.pooler.supabase.com:6543

    user: postgres.mroadgdwswjvikvjhldv

    secureJsonData:
      password: airIOC2026@

    jsonData:
      database: postgres
      sslmode: require
      postgresVersion: 1500

    isDefault: true